spring:
  application:
    name: interview-grpc-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# Interview Configuration
interview:
  # Recording settings
  recordings-dir: recordings
  max-recording-size-mb: 50
  audio-format: mp3
  audio-quality: high
  
  # Session settings
  session-timeout-minutes: 60
  auto-cleanup-days: 30
  
  # Whisper settings
  whisper-model: base
  
  # Server settings
  host: 0.0.0.0
  port: 9090
  debug: true
  
  # Metadata settings
  save-transcription: true
  save-audio-duration: true
  save-audio-quality: true
  
  # File naming patterns
  audio-filename-pattern: response_{timestamp}.{ext}
  metadata-filename-pattern: metadata_{timestamp}.json
  session-id-pattern: interview_{date}_{time}_{client_suffix}
  
  # Combined audio settings
  create-combined-audio: false
  combined-audio-filename: combined_interview.mp3
  
  # Backup settings
  auto-backup: false
  backup-dir: backups
  backup-interval-hours: 24
  
  # Security settings
  allowed-origins: "*"
  require-authentication: false
  api-key: null
  
  # OpenAI settings
  openai-api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
  openai-model: gpt-3.5-turbo
  openai-max-tokens: 150
  openai-temperature: 0.7
  use-openai-for-interview: true
  
  # OpenAI TTS settings
  use-openai-tts: true
  openai-tts-voice: alloy
  openai-tts-model: tts-1
  
  # gRPC settings
  grpc-port: 9090
  max-message-size: 52428800  # 50MB

# Logging
logging:
  level:
    com.interview: DEBUG
    io.grpc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Server
server:
  port: 8080  # HTTP server port (for health checks, etc.) 